name: bachelor
description: "Frontend for clothing recommendation system"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
    
  english_words: ^4.0.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  emoji_extension: ^1.2.0
  http: ^0.13.6
  shared_preferences: ^2.2.2
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  image_picker: ^1.1.2
  jwt_decoder: ^2.0.1
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/default_avatar.jpg

